/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.establishmentInformation;

import java.awt.event.ActionListener;

/**
 *
 * @author aca
 */
public class EstablishmentInformationDialog extends javax.swing.JDialog {

    /**
     * Creates new form computerServiceDialog
     */
    public EstablishmentInformationDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        establishmentInformationLabel = new javax.swing.JLabel();
        hrLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        employeesNumberSpinner = new javax.swing.JSpinner();
        employeesNumberLabel = new javax.swing.JLabel();
        cleanButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        saveButton.setText("Save");
        saveButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 102), 1, true));
        saveButton.setPreferredSize(new java.awt.Dimension(70, 21));

        editButton.setText("Edit");

        cancelButton.setText("Cancel");

        establishmentInformationLabel.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        establishmentInformationLabel.setText("Establishment Information");

        hrLabel.setText("________________________________________________");

        nameLabel.setText("Name:");

        addressLabel.setText("Address:");

        phoneLabel.setText("Telephone number:");

        addressTextField.setToolTipText("Introduce the address of the establishment");

        nameTextField.setToolTipText("Introduce the establishment name");

        phoneTextField.setToolTipText("Introduce the establishment telephone ");

        employeesNumberSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        employeesNumberSpinner.setToolTipText("Introduce the number of employees from the establishment");

        employeesNumberLabel.setText("Number of employees:");

        cleanButton.setText("Clean");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cleanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(establishmentInformationLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameLabel)
                            .addComponent(addressLabel)
                            .addComponent(phoneLabel)
                            .addComponent(employeesNumberLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(employeesNumberSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(addressTextField)
                            .addComponent(phoneTextField)
                            .addComponent(nameTextField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(establishmentInformationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneLabel)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nameLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeesNumberSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeesNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cleanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public void addSaveButtonActionListener(ActionListener al){
        this.saveButton.addActionListener(al);
    }
    
    public void addEditButtonActionListener(ActionListener al){
        this.editButton.addActionListener(al);
    }
    
    public void addCleanButtonActionListener(ActionListener al){
        this.cleanButton.addActionListener(al);
    }
    
    public void addCancelButtonActionListener(ActionListener al){
        this.cancelButton.addActionListener(al);
    }
    
    public void setButtonDisabled(String button){
        if(button=="save"){
            this.saveButton.setEnabled(false);
        }else if(button=="clean"){
            this.cleanButton.setEnabled(false);
        }else if(button=="edit"){
            this.editButton.setEnabled(false);
        }else{
            System.err.println("Error in setButtonDisabled");
        }
    }
    
    public void setButtonEnabeled(String button){
        if(button=="save"){
            this.saveButton.setEnabled(true);
        }else if(button=="edit"){
            this.editButton.setEnabled(true);
        }else if(button=="clean"){
            this.cleanButton.setEnabled(true);
        }else{
            System.err.println("Error in setButtonDisabled");
        }
    }
    
    public String getCancelButtonName(){
        return this.cancelButton.getText();
    }
    
    public void setCancelButtonName(String name){
        this.cancelButton.setText(name);
    }
    
    
    public String getName(){
        return this.nameTextField.getText();
    }
    
    public void setName(String name){
        this.nameTextField.setText(name);
    }
    
    
    public String getAddress(){
        return this.addressTextField.getText();
    }
    
    public void setAddress(String address){
        this.addressTextField.setText(address);
    }
    
    
    public String getPhone(){
        return this.phoneTextField.getText();
    }
    
    public void setPhone(String phone){
        this.phoneTextField.setText(phone);
    }
    
    
    public int getEmployeesNumber(){
        return (int) this.employeesNumberSpinner.getValue();
    }
    
    public void setEmployeesNuber(int employeesNumber){
        this.employeesNumberSpinner.setValue(employeesNumber);
    }
    
    public void setTextFieldsDisabled(){
        this.nameTextField.setEnabled(false);
        this.addressTextField.setEnabled(false);
        this.phoneTextField.setEnabled(false);
        this.employeesNumberSpinner.setEnabled(false);
    }
    
    public void setTextFieldsEnabled(){
        this.nameTextField.setEnabled(true);
        this.addressTextField.setEnabled(true);
        this.phoneTextField.setEnabled(true);
        this.employeesNumberSpinner.setEnabled(true);
    }
    
    public void cleanTextFields(){
        this.nameTextField.setText("");
        this.addressTextField.setText("");
        this.phoneTextField.setText("");
        this.employeesNumberSpinner.setValue(0);
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cleanButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel employeesNumberLabel;
    private javax.swing.JSpinner employeesNumberSpinner;
    private javax.swing.JLabel establishmentInformationLabel;
    private javax.swing.JLabel hrLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
